server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id : USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/users/**

          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/api/hotels/**

          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/api/ratings/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL for service registration and discovery
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true