server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: rohit@001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085
  #  profiles:
  #    active:
  #      - dev

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # Eureka server URL for service registration and discovery
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true